logging:
  config: classpath:conf/logback-dev.xml
  level:
    org.springframework.security: debug
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS
    shutdown:
      enabled: true
server:
  port: 9001
  http2:
    enabled: true
  undertow:
    buffer-size: 1024
    direct-buffers: true
spring:
  servlet:
    multipart:
      max-file-size: 10MB # 最大附件大小
      max-request-size: 10MB
  main:
    allow-bean-definition-overriding: true
  mvc:
    static-path-pattern: /static/**
  cache:
    redis:
      use-key-prefix: true
      time-to-live: 1d
  security:
    oauth2:
      client:
        registration:
          github:
            # http://localhost:9001/oauth2/authorization/github
            client-id: 85be31954323df1dd95f
            client-secret: e79350fa501cdda62efba260ffc861807ce47af0
          bali:
            provider: bali
            client-id: bali-client
            client-secret: bali-secret
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope: message.read,message.write
        provider:
          bali:
            jwk-set-uri: http://127.0.0.1:9000/.well-known/jwks.json
            authorization-uri: http://127.0.0.1:9000/oauth/authorize
            token-uri: http://127.0.0.1:9000/oauth/token
            user-info-uri: http://127.0.0.1:9000/resource/user-info
            user-info-authentication-method: header
            user-name-attribute: name
  redis:
    host: 127.0.0.1
    password:
    port: 6379
    lettuce:
      shutdown-timeout: 100
      pool:
        max-active: 8
        max-idle: 8
        max-wait: 30
        min-idle: 0
    # 选择数据库
    database: 0