logging:
  config: classpath:conf/logback-prd.xml
springdoc:
  swagger-ui:
    display-request-duration: true
    groups-order: DESC
    operationsSorter: method
    path: /swagger-ui.html
    enabled: true
  show-actuator: true
  api-docs:
    version: openapi_3_0
    path: /v3/api-docs
    enabled: true
management:
  endpoint:
    health:
      probes:
        enabled: true
  endpoints:
    web:
      exposure:
        include: info,health
    enabled-by-default: true
server:
  port: 9000
  http2:
    enabled: true
  undertow:
    buffer-size: 1024
    direct-buffers: true
spring:
  servlet:
    multipart:
      max-file-size: 10MB # 最大附件大小
      max-request-size: 10MB
      location: /data/tmp/application
  mvc:
    static-path-pattern: /static/**
  cache:
    redis:
      use-key-prefix: true
      time-to-live: 1d
  redis:
    host: 127.0.0.1
    password: ENC('E9RmN2/nnGsqK5wPxaJ1xkDggIMpFADAZ33gjSM09iM=')
    port: 6379
    lettuce:
      shutdown-timeout: 100
      pool:
        max-active: 8
        max-idle: 8
        max-wait: 30
        min-idle: 0
    database: 0
  liquibase:
    enabled: false
  datasource:
    name: bali-user-center
    url: jdbc:mysql://rm-uf6641sh998vextvw.mysql.rds.aliyuncs.com:3306/bali_user_center?characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: ENC('XKhzB39YUJbyjjYT6SApDDh/dhY+2lCe')
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      filters: stat
      max-active: 200
      initial-size: 1
      max-wait: 60000
      min-idle: 1
      time-between-eviction-runs-millis: 60000
      min-evictableIdle-time-millis: 300000
      validation-query: select 'x'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-open-prepared-statements: 20
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  type-aliases-package: com.github.bali.auth.entity
  check-config-location: true
  global-config:
    banner: false
    db-config:
      capital-mode: false
      id-type: ASSIGN_ID
      logic-delete-value: 'null'
      logic-not-delete-value: '0'
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true
    call-setters-on-nulls: true
multi-tenancy:
  table-field: tenant_id # 租户标识字段
  ignore:
    roles:
      - SUPER_ADMIN # 超级管理员直接忽略租户控制
    tables: # 不需要租户控制的表
      - uc_tenant
      - uc_user_role
      - uc_auth_client_details_scope
      - v_role_view
attachment:
  api: enable
  cloud:
    aliyun:
      name: user-center-aliyun
      root: user-center
      endpoint: oss-cn-shanghai.aliyuncs.com
      access-key-id: ENC('5YHpnBeUFMA9g50jT9Ng2o8mfoCx4Z3W6n4hEYOS8iZjv/JY0swpBg==')
      access-key-secret: ENC('R+4aRIrz0CpSvUHtyW+DZNY33PE/+Ce5Ep26JMS1xq2WmzBcqVlyAw==')
      bucket: user-center-attachment
  local:
    name: user-center-local
    root: file/
authorize:
  enable-password-encrypt: false
  encrypt-key: 'qtcc2MNMsavbqQWa'
  login-attempt:
    enable: true
    times-before-lock: 5
    granters:
      - password
      - captcha_password
